# we don't need path labels here but the bot expects atleast one row inside it.
# This compulsion will be removed after https://issues.redhat.com/browse/KOGITO-3026

labels:
  - paths:
      - anything/**
    labels:
      - "won't trigger"

default:
  - 'needs review :mag:'